### ISSUE TITLE
bug in `reduce`

### ISSUE THREAD

**Issue by suukii** [RyanAmeri/FrontEnd-Masters#2]
https://github.com/RyanAmeri/FrontEnd-Masters/blob/6caa229c2e1fe24fee8d41ee89565c8f3376c045/js_the_hard_parts_v2/callback_exercises.js#L83

The case where `initialValue` is not provided is not considered.

When `initialValue` is initialized as `array[0]`, the callback function will receive `(array[0], array[0])` as its arguments in first iteration.

**Comment by RyanAmeri** [comment]
Thank you for the bug report! Should be fixed now!
